# Generated by Django 5.1.1 on 2024-10-07 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=100000.0, max_digits=15, null=True),
        ),
    ]
