# Generated by Django 5.1.1 on 2024-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Completed', 'Partially Completed'), ('Fully Completed', 'Fully Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
