# Generated by Django 5.1.1 on 2024-11-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_trade_profit_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='related_entity_id',
        ),
    ]
