# Generated by Django 5.1.1 on 2024-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_transactionlog_related_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='order',
        ),
        migrations.AlterField(
            model_name='dividend',
            name='budget_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='dividend_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
