# Generated by Django 5.1.1 on 2024-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_trade_order_alter_dividend_budget_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='max_trader_buy_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
